version: '3.8'
services:
  postgres-db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SOURCE_HOST=${POSTGRES_SOURCE_HOST}
    ports:
      - '5432:5432'    
    volumes: 
      - dev_db:/var/lib/postgresql/data
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
volumes:
  dev_db: # Volume name appended to the -p flag for profile name. Must match volumes: string above
    driver: local